language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-25
before_script:
  - sudo apt-get install ant
script:
  - cd eclipse/library
  - ant clean
  - ant
  - cd ../sample
  - ant clean
  - ant
