language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-25
script:
  - cd eclipse/library
  - ant clean
  - ant
  - cd ../sample
  - ant clean
  - ant
